config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'

  get 'static_pages/top'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy', as: 'logout'

  resources :users do
    member do
      resource :guidelines, only: [:create]
      resources :tags, only: [:create, :update, :destroy]
        scope module: :tags do
          resource :base_tags, only: [:update]
          resource :page_transitions, only: [:show], as: :tags_transitions
          resource :question_assistances, only: [:new, :create, :update]
        end
      resource :target, only: [:create, :update, :destroy]
        scope module: :targets do
          resource :target_transitions, only: [:show], as: :targets_transitions
        end
      resource :company
        scope module: :companies do
          resources :company_transitions, only: [:show], as: :company_transitions
          resources :company_seraches, only: [:index, :show], as: :company_serach
        end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password validations: true
  has_many :tag, dependent: :destroy
  has_many :target, dependent: :destroy
  has_many :company, dependent: :destroy
  has_one :guideline, dependent: :destroy

  # バリデーション
  validates :name, presence: true, length: { maximum: 30 }
  # メールアドレスの形か判定するための変数
  email_check = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: email_check }
  validates :password, length: { minimum: 6 }, on: :create

  # トークン作成(英数+URLで使用可能な文字列の乱数生成)
  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  # 乱数を暗号化(ハッシュ値生成)
  def self.encrypt(token)
    Digest::SHA256.hexdigest(token.to_s)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login!, only: [:new, :create]

  def index
    @user = User.new
  end

  def new
    @user = User.new
  end

  def show
    set_instance
    @target = Target.new
  end

  # サインアップ処理 => DBにuser_paramsからのデータを保存
  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to user_path(@user.id), notice: "#{@user.name}さん！登録が完了しました。"
    else
      render :new
    end
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_instance
    @tag = Tag.new
    @will_tags = @current_user.tag.where(wcm: 'will')
    @can_tags = @current_user.tag.where(wcm: 'can')
    @must_tags = @current_user.tag.where(wcm: 'must')
    @will_base = @current_user.tag.find_by(wcm: 'will', base_tag: true)
    @can_base = @current_user.tag.find_by(wcm: 'can', base_tag: true)
    @must_base = @current_user.tag.find_by(wcm: 'must', base_tag: true)
    @guideline = Guideline.find_or_initialize_by(user_id: @current_user.id).presence || Guideline.new
    @targets = Target.where(user_id: @current_user).time_order
    @companies = Company.where(user_id: @current_user.id)
    @company = @current_user.company.new
  end
end

app/views/users/_wcm_tags.html.erb
<div class="modal fade" id="wcm-tagsModal" tabindex="-1" role="dialog" aria-labelledby="wcm-tagsModal" aria-hidden="true">
  <div class="modal-dialog modal-xl" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title h3" id="wcm-tagsModalLabel">
          <i class="fas fa-tags"></i>
          WCMタグ編集
        </h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item">
              <%= link_to "Will", page_transition_user_path(transition_value: "will"),class: "nav-link",data: {toggle: "tab"}, role: "tab",aria:{selected: true}, id: "will-active", remote: true %>
            </li>
            <li class="nav-item">
              <%= link_to "Can", page_transition_user_path(transition_value: "can"), class: "nav-link", data: { toggle: "tab" }, role: "tab", aria: { selected: true }, id: "can-active", remote: true %>
            </li>
            <li class="nav-item">
              <%= link_to "Must", page_transition_user_path(transition_value: "must"), class: "nav-link", data: { toggle: "tab" }, role: "tab", aria: { selected: true }, id: "must-active", remote: true %>
            </li>
          </ul>
          <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="wcm-container" role="tabpanel" aria-labelledby="home-tab">
              <%= render partial: 'will_tags.html.erb' %>
            </div>
          </div>
        </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>

app/views/users/_will_tags.html.erb
<div class="row tags-edit">
  <div class="col-12 tags">
    <h3 class="h3">
      <i class="far fa-eye"></i>
      表示タグ
    </h3>
    <%= form_with model: @tag, url: tag_delete_user_path, method: :delete do |f| %>
      <div class="tags-container" id="tagContainer">
        <%= render partial: "tags/tags_show", locals: { instance: @tags, f: f } %>
      </div>
      <div class="col-12 text-right">
        <input type="button" class="btn btn-success" id="select-btn" value="選択" data-display="false" onclick="selectDisplay()">
        <%= f.submit "削除",class: 'btn btn-danger d-none', id: 'delete-btn', onclick: "deleteEnter()" %>
      </div>
    <% end %>
  </div>

  <div class="col-12 edit">
    <h3 class="h3">
      <i class="fas fa-pen-square"></i>
      編集
    </h3>
    <div class="edit-js-message-errors"></div>
    <div id="blank-tag-container">
      <button type="button" class="btn btn-secondary modal-btn" id="blank-tag">none</button>
    </div>
    <%= form_with model: @tag, url: tag_edit_user_path, class: "js-form" do |f| %>
      <%= f.hidden_field :id %>
      <%= f.label :name, "質問の編集:", for: "edit-textarea" %>
      <%= f.text_area :question_body, class: "form-control", id: "edit-textarea"%>
      <%= f.text_field :tag, placeholder: "解答タグの編集", class: "form-control", id: "edit-textfield" %>
      <div class="col-12 text-right">
        <%= f.submit "更新", class: 'btn btn-success', id: "edit-submit", disabled: true, onclick: "editEnter()" %>
      </div>
    <% end %>
  </div>

  <div class="col-12 new">
    <h3 class="h3">
      <i class="fas fa-plus-square"></i>
      新規作成
    </h3>
    <div class="create-js-message-errors"></div>
    <%= form_with model: @tag, url: tag_new_user_path(@current_user.id) do |f| %>
      <%= f.label :name, '質問の新規作成', for: 'create-textarea' %>
      <%= f.text_area :question_body, class: 'form-control', id: 'create-textarea' %>
      <%= f.text_field :tag, placeholder: '解答タグの新規作成', class: 'form-control', id: 'create-textfield' %>
      <%= f.hidden_field :wcm, value: @transition_value %>
      <div class="col-12 text-right">
        <%= f.submit "作成", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="row signup">
	<%= form_with model: @user, url: users_path, local: true, class: 'col-12 col-md-6' do |f| %>
		<h2>Signup</h2>
		<%= render partial: 'layouts/errors', locals: {instance: @user} %>
		<div class="form-group">
			<%= f.label :name, 'ユーザー名', for: 'InputName' %>
			<%= f.text_field :name, class: "form-control", id: 'InputName' %>
		</div>
		<div class="form-group">
			<%= f.label :email, 'メールアドレス', for: 'InputEmail' %>
			<%= f.text_field :email, class: "form-control", id: 'InputEmail' %>
		</div>
		<div class="form-group">
			<%= f.label :password, 'パスワード', for: 'InputPassword' %>
			<%= f.text_field :password, type: 'password', class: "form-control", id: 'InputPassword' %>
		</div>
		<div class="form-group">
			<%= f.label :password_confirmation, 'パスワード再確認', for: 'InputPasswordConfirmation' %>
			<%= f.text_field :password_confirmation, type: 'password', class: "form-control", id: 'InputPasswordConfirmation' %>
		</div>
		<%= f.submit 'Signup', type: 'submit', class: "btn btn-success btn-lg" %>
	<% end %>
</div>

app/views/users/show.html.erb
<div class="row mx-1 user_work_space">
  <div class="col-12 flash">
    <%= render partial: 'layouts/flash' %>
  </div>
  <%= render partial: 'users/wcm_seat/modal/modal_show' %>
  <%= render partial: 'users/base_tags/modal/base_tags' %>
  <%= render partial: "users/target/modal/modal_target" %>
  <%= render partial: "users/companies/modal/create/modal_companies" %>
  <%= render partial: "users/companies/modal/edit/modal_companies" %>

  <section class="wcm-seat">
    <div class="row wcm-work-space">
            <div class="col-12">
              <h2 class="h2">WCMシート</h2>
            </div>
        <div class="col-12 wcm-chart">
        <div class="row">
            <div class="col-12 col-md-4 will-chart chart">
              <p>Will</p>
              <div class="row mx-md-1 will-tags tags" id="will-seat">
                <%= render partial: "users/wcm_seat/wcm_seat_tags", locals: { instance: @will_tags, tags_wcm: "will" } %>
              </div>
            </div>

            <div class="col-12 col-md-4 can-chart chart">
              <p>Can</p>
              <div class="row mx-md-1 can-tags tags" id="can-seat">
                <%= render partial: "users/wcm_seat/wcm_seat_tags", locals: { instance: @can_tags, tags_wcm: "can" } %>
              </div>
            </div>

            <div class="col-12 col-md-4 must-chart chart">
              <p>Must</p>
              <div class="row mx-md-1 must-tags tags" id="must-seat">
                <%= render partial: "users/wcm_seat/wcm_seat_tags", locals: { instance: @must_tags, tags_wcm: "must" } %>
              </div>
            </div>
          </div>
        </div>

        <div class="col-12 wcm-result">
          <h3 class="col-12 h3">ベースタグ</h3>
          <div class="row" id="base-tags">
            <%= render partial: "users/base_tags/base_tags_btn" %>
          </div>
          <div class="guideline">
            <h3 class="h3">WCMからの行動指標</h3>
            <div class="guideline-container" data-toggle="modal" data-target=".bd-example-modal-xl" id="guideline-container">
              <%= render "users/base_tags/modal/modal_guideline_text", text: @guideline.text %>
            </div>
          </div>
        </div>
      </div>
      <div class="text-right w-100 mt-2 mb-5">
        <a><i class="fas fa-arrow-right pr-2"></i>他のユーザーのWCMを見る</a>
      </div>
    </div>
  <section>

  <section class="col-12 wcm-target">
    <div class="row mb-3" id="target-show">
      <%= render 'users/target/target' %>
    </div>
  </section>

  <section class="col-12 company-analysis">
    <div class="row">
      <%= render 'users/companies/companies' %>
    </div>
  </section>
</div>