config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'

  get 'static_pages/top'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy', as: 'logout'

  resources :users do
    member do
      resource :guidelines, only: [:create]
      resources :tags, only: [:create, :update, :destroy]
        scope module: :tags do
          resource :base_tags, only: [:update]
          resource :page_transitions, only: [:show], as: :tags_transitions
          resource :question_assistances, only: [:new, :create, :update]
        end
      resource :target, only: [:create, :update, :destroy]
        scope module: :targets do
          resource :target_transitions, only: [:show], as: :targets_transitions
        end
      resource :company
        scope module: :companies do
          resources :company_transitions, only: [:show], as: :company_transitions
          resources :company_seraches, only: [:index, :show], as: :company_serach
        end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, length: { maximum: 30 }
  validates :url, presence: true
  validates :url, format: /\A#{URI::regexp(%w(http https))}\z/

  with_options length: { maximum: 3000 } do
    validates :business,
              :culture,
              :vision,
              :future,
              :skill,
              :treatment
  end
  with_options numericality: { only_integer: true, greater_than: 0, less_than: 6 } do
    validates :business_fit,
              :culture_fit,
              :vision_fit,
              :future_fit,
              :skill_fit,
              :treatment_fit
  end

  scope :sorted, -> { order(created_at: :desc) }

  def aspiration
    result = [
      business_fit,
      culture_fit,
      vision_fit,
      future_fit,
      skill_fit,
      treatment_fit,
    ]
    result.sum
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password validations: true
  has_many :tag, dependent: :destroy
  has_many :target, dependent: :destroy
  has_many :company, dependent: :destroy
  has_one :guideline, dependent: :destroy

  # バリデーション
  validates :name, presence: true, length: { maximum: 30 }
  # メールアドレスの形か判定するための変数
  email_check = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: email_check }
  validates :password, length: { minimum: 6 }, on: :create

  # トークン作成(英数+URLで使用可能な文字列の乱数生成)
  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  # 乱数を暗号化(ハッシュ値生成)
  def self.encrypt(token)
    Digest::SHA256.hexdigest(token.to_s)
  end
end

app/controllers/companies/company_seraches_controller.rb
class Companies::CompanySerachesController < ApplicationController
  def index
    @sort_companies = @q.result
    respond_to do |format|
      format.js { render template: "users/companies/sort_companies" }
    end
  end

  def show
    respond_to do |format|
      format.js { render template: "users/companies/serach_companies" }
    end
  end
end

app/controllers/companies/company_transitions_controller.rb
class Companies::CompanyTransitionsController < ApplicationController
  def show
    @company = @current_user.company.find(params[:transition_value])
    respond_to do |format|
      format.js { render template: "users/companies/modal/edit/_transition_dstination" }
    end
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def create
    @company = @current_user.company.new(companies_params)
    respond_to do |format|
      if @company.save
        format.js { flash.now[:success] = "#{@company.name}を登録しました。" }
      else
        format.js { render :create_errors }
      end
      set_instance
    end
  end

  def update
    @company = Company.find(companies_params[:id])
    respond_to do |format|
      if @company.update(companies_params)
        format.js { flash.now[:success] = "#{@company.name}を更新しました。" }
      else
        format.js { render :update_errors }
      end
    end
    set_instance
  end

  def destroy
    if select_companies_params.present?
      respond_to do |format|
        select_companies_params.each do |company|
          @company = @current_user.company.find(company)
          if @company.delete
            format.js { flash.now[:success] = "削除しました。" }
          else
            format.js { flash.now[:success] = "削除できませんでした。" }
          end
        end
      end
    else
      flash.now[:success] = "企業を選択してください。"
    end
    set_instance
  end

  private

  def companies_params
    params.require(:company).permit(:id,
                                    :name,
                                    :url,
                                    :business,
                                    :business_fit,
                                    :culture,
                                    :culture_fit,
                                    :vision,
                                    :vision_fit,
                                    :future,
                                    :future_fit,
                                    :skill,
                                    :skill_fit,
                                    :treatment,
                                    :treatment_fit,)
  end

  def select_companies_params
    ids = params.fetch(:company, {}).permit(companies_ids: [])
    ids.values[0]
  end

  def set_instance
    @companies = Company.where(user_id: @current_user.id).sorted
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login!, only: [:new, :create]

  def index
    @user = User.new
  end

  def new
    @user = User.new
  end

  def show
    set_instance
    @target = Target.new
  end

  # サインアップ処理 => DBにuser_paramsからのデータを保存
  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to user_path(@user.id), notice: "#{@user.name}さん！登録が完了しました。"
    else
      render :new
    end
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_instance
    @tag = Tag.new
    @will_tags = @current_user.tag.where(wcm: 'will')
    @can_tags = @current_user.tag.where(wcm: 'can')
    @must_tags = @current_user.tag.where(wcm: 'must')
    @will_base = @current_user.tag.find_by(wcm: 'will', base_tag: true)
    @can_base = @current_user.tag.find_by(wcm: 'can', base_tag: true)
    @must_base = @current_user.tag.find_by(wcm: 'must', base_tag: true)
    @guideline = Guideline.find_or_initialize_by(user_id: @current_user.id).presence || Guideline.new
    @targets = Target.where(user_id: @current_user).time_order
    @companies = Company.where(user_id: @current_user.id)
    @company = @current_user.company.new
  end
end

app/helpers/companies/company_search_helper.rb
module Companies::CompanySearchHelper
end

app/helpers/companies/company_transitions_helper.rb
module Companies::CompanyTransitionsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/users/companies/_companies.html.erb
<div class="col-12">
  <h2 class="h2">企業分析</h2>

  <%= search_form_for @q, url: company_serach_path, remote: true, html: {class: "search_container text-right"} do |f| %>
    <%= f.search_field :name_cont, type: "text", placeholder: "企業検索" %>
    <input type="submit" class="fas search_container-submit" value="&#xf002;">
  <% end %>
  <div class="table-responsive-lg companies-show">
    <%= render partial: "users/companies/companies_show", locals: { instance: @companies } %>
  </div>
  <div class="companies-create mt-3 mb-5 text-right">
    <button type="button" class="btn btn-success" id="company-create" data-toggle="modal" data-target=".modal_companies">新規作成/削除</button>
  <div>
</div>

app/views/users/companies/_companies_show.html.erb
<table class="table table-hover text-center show-table" id="company-show-table">
  <thead>
    <% url_options = { controller: "companies/company_seraches", action: :index } %>
    <% html_options = { remote: true, class: "text-white" } %>
    <tr class="compnay-color text-white">
      <th scope="col"><%= sort_link @q, :name, "企業名",url_options, html_options %></th>
      <th scope="col">URL</th>
      <th scope="col"><%= sort_link @q, :business_fit, "事業",url_options, html_options %></th>
      <th scope="col"><%= sort_link @q, :culture_fit, "社風/環境",url_options, html_options %></th>
      <th scope="col"><%= sort_link @q, :vision_fit, "ビジョン",url_options, html_options %></th>
      <th scope="col"><%= sort_link @q, :future_fit, "将来性",url_options, html_options %></th>
      <th scope="col"><%= sort_link @q, :skill_fit, "スキル",url_options, html_options %></th>
      <th scope="col"><%= sort_link @q, :treatment_fit, "待遇",url_options, html_options %></th>
      <th scope="col">志望度</th>
    </tr>
  </thead>
  <tbody>
    <% instance.each do |company| %>
      <tr>
        <td class="p-0" id="edit-company-id<%= company.id %>">
          <%= link_to company.name, company_transition_path(transition_value: company.id), class: "d-block p-2 text-dark company-index", data: { toggle: "modal", target: ".edit_modal_companies" }, remote: true %>
        </td>
        <td class="p-0">
          <%= link_to "URL", company.url, class: "d-block p-2", target: "blank", rel: "noopener noreferrer" %>
        </td>
        <td class="p-0"><%= link_to company.business_fit, company_transition_path(transition_value: company.id), class: "d-block p-2 text-dark company-index", data: { toggle: "modal", target: ".edit_modal_companies" }, remote: true %></td>
        <td class="p-0"><%= link_to company.culture_fit, company_transition_path(transition_value: company.id), class: "d-block p-2 text-dark company-index", data: { toggle: "modal", target: ".edit_modal_companies" }, remote: true %></td>
        <td class="p-0"><%= link_to company.vision_fit, company_transition_path(transition_value: company.id), class: "d-block p-2 text-dark company-index", data: { toggle: "modal", target: ".edit_modal_companies" }, remote: true %></td>
        <td class="p-0"><%= link_to company.future_fit, company_transition_path(transition_value: company.id), class: "d-block p-2 text-dark company-index", data: { toggle: "modal", target: ".edit_modal_companies" }, remote: true %></td>
        <td class="p-0"><%= link_to company.skill_fit, company_transition_path(transition_value: company.id), class: "d-block p-2 text-dark company-index", data: { toggle: "modal", target: ".edit_modal_companies" }, remote: true %></td>
        <td class="p-0"><%= link_to company.treatment_fit, company_transition_path(transition_value: company.id), class: "d-block p-2 text-dark company-index", data: { toggle: "modal", target: ".edit_modal_companies" }, remote: true %></td>
        <td class="p-0"><%= link_to company.aspiration, company_transition_path(transition_value: company.id), class: "d-block p-2 text-dark company-index", data: { toggle: "modal", target: ".edit_modal_companies" }, remote: true %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/companies/serach_companies.js.erb
<%# 検索結果の出力 %>
$('.companies-show').html("<%= j(render partial: "users/companies/companies_show", locals: { instance: @search_conpanies }) %>");

app/views/users/companies/serach_company.js.erb
<%# 検索結果の出力 %>
$('.companies-show').html("<%= j(render partial: "users/companies/companies_show", locals: { instance: @search_conpanies }) %>");

app/views/users/companies/sort_companies.js.erb
<%# ソート結果の出力 %>
$('.companies-show').html("<%= j(render partial: "users/companies/companies_show", locals: { instance: @sort_companies }) %>");