config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'

  get 'static_pages/top'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy', as: 'logout'

  resources :users do
    member do
      resource :guidelines, only: [:create]
      resources :tags, only: [:create, :update, :destroy]
        scope module: :tags do
          resource :base_tags, only: [:update]
          resource :page_transitions, only: [:show], as: :tags_transitions
          resource :question_assistances, only: [:new, :create, :update]
        end
      resource :target, only: [:create, :update, :destroy]
        scope module: :targets do
          resource :target_transitions, only: [:show], as: :targets_transitions
        end
      resource :company
        scope module: :companies do
          resources :company_transitions, only: [:show], as: :company_transitions
          resources :company_seraches, only: [:index, :show], as: :company_serach
        end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :user
  # バリデーション
  validates :question_body, presence: true, length: { maximum: 50 }
  validates :tag, presence: true, length: { maximum: 10 }
  validate :wcm, :wcm_check
  validate :wcm, :limit_check, on: :create

  # スコープ
  scope :tags, -> (wcm) { where(wcm: wcm) }
  scope :sorted, -> { order(created_at: :desc) }
  scope :recent, -> (wcm) { tags(wcm).sorted }
  # nil許容のため、scopeではなくメソッド定義とした
  def self.base(wcm)
    find_by(wcm: wcm, base_tag: true)
  end

  private

  def wcm_check
    unless wcm == "will" || wcm == "can" || wcm == "must"
      errors.add(:wcm, "不正な値を検出しました")
    end
  end

  # タグの数が６以下なら保存
  def limit_check
    case wcm
    when "will"
      tags = Tag.where(user_id: user_id, wcm: "will")
      if tags.count >= 6
        errors.add(:wcm, "のタグの登録は、それぞれ６件までです")
      end
    when "must"
      tags = Tag.where(user_id: user_id, wcm: "must")
      if tags.count >= 6
        errors.add(:wcm, "のタグの登録は、それぞれ６件までです")
      end
    when "can"
      tags = Tag.where(user_id: user_id, wcm: "can")
      if tags.count >= 6
        errors.add(:wcm, "のタグの登録は、それぞれ６件までです")
      end
    else
      errors.add(:wcm, "不正な値です")
    end
  end
end

app/controllers/tags/base_tags_controller.rb
class Tags::BaseTagsController < ApplicationController
  def update
    new_base_tag = base_tag_params
    old_base_tag = @current_user.tag.where(base_tag: true)
    respond_to do |format|
      if new_base_tag
        old_base_tag.update(base_tag: false)
        new_base_tag.each do |id|
          tag = Tag.find(id)
          tag.update(base_tag: true)
            format.js { flash.now[:success] = "ベースタグをアップデートしました。" }
        end
      else
        format.js { flash.now[:success] = "ベースタグを選択してください" }
      end
      set_tags
    end
  end

  private

  def base_tag_params
    ids = params.fetch(:tag, {}).permit(base_tag: [])
    ids.values[0]
  end

  def set_tags
    @will_tags = @current_user.tag.recent("will")
    @can_tags = @current_user.tag.recent("can")
    @must_tags = @current_user.tag.recent("must")
    @will_base = @current_user.tag.base("will")
    @can_base = @current_user.tag.base("can")
    @must_base = @current_user.tag.base("must")
  end
end

app/controllers/tags/page_transitions_controller.rb
class Tags::PageTransitionsController < ApplicationController
  def show
    @tag = @current_user.tag.new
    @transition_value = params[:transition_value]
    @tags = @current_user.tag.tags(@transition_value)
    respond_to do |format|
      if @transition_value == "will" || @transition_value == "can" || @transition_value == "must"
        format.js { render template: "users/wcm_seat/modal/transition_destination" }
      else
        render template: "users/show"
        flash.now[:success] = "不正な遷移指定です"
      end
    end
  end
end

app/controllers/tags/question_assistances_controller.rb
class Tags::QuestionAssistancesController < ApplicationController
  def new
    @tag = Tag.new
  end

  def create
    @tag = @current_user.tag.build(assistances_tags_params)
    respond_to do |format|
      if @tag.save
        format.js { flash.now[:notice] = "タグを作成しました。" }
      else
        format.js { render :create_errors }
      end
    end
  end

  def update

  end

  private

  def assistances_tags_params
    params.require(:tag).permit(:id, :question_body, :tag, :wcm)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def create
    @tag = @current_user.tag.build(tags_params)
    respond_to do |format|
      if @tag.save
        format.js { flash.now[:success] = "タグを作成しました。" }
      else
        format.js { render :create_errors }
      end
    end
    @tags = @current_user.tag.tags(@tag.wcm)
    set_instance
  end

  def update
    @tag = @current_user.tag.find(tags_params[:id])
    respond_to do |format|
      if @tag.update(tags_params)
        format.js { flash.now[:success] = "タグを更新しました。" }
      else
        format.js { render :edit_errors }
      end
    end
    @tags = @current_user.tag.tags(@tag.wcm)
    set_instance
  end

  def destroy
    if select_tags_params.present?
      select_tags = select_tags_params
      respond_to do |format|
        select_tags.each do |t|
          t = Tag.find(t)
          @value = t.wcm
          @tags = @current_user.tag.tags(t.wcm)
          if t.destroy
            format.js { flash.now[:success] = "タグを削除しました。" }
          else
            format.js { flash.now[:success] = "タグを削除できませんでした。" }
          end
        end
      end
    else
      @transition_value = params[:transition_value]
      @tags = @current_user.tag.tags(@transition_value)
      flash.now[:success] = "タグを選択してください"
    end
    set_instance
  end

  private

  def tags_params
    params.require(:tag).permit(:id, :question_body, :tag, :wcm)
  end

  def select_tags_params
    ids = params.fetch(:tag, {}).permit(tags_ids: [])
    ids.values[0]
  end

  def set_instance
    @will_tags = @current_user.tag.recent("will")
    @can_tags = @current_user.tag.recent("can")
    @must_tags = @current_user.tag.recent("must")
    @will_base = @current_user.tag.base("will")
    @can_base = @current_user.tag.base("can")
    @must_base = @current_user.tag.base("must")
  end
end

app/helpers/question_assistances_helper.rb
module QuestionAssistancesHelper
    def any_of_wcm
    [
      "will",
      "will",
      "will",
      "can",
      "can",
      "can",
      "must",
      "must",
      "must",
    ]
  end

  def questions
    {
      "理想の将来像を入力しましょう" => "あなたは将来、なりたいものはありますか？",
      "人生の中で一番重要視しているものを入力しましょう" => "スキル、お金、時間何を重視しますか？(この他でも解答可)",
      "その人のどういうところを目標としたいのか理由を入力しましょう" => "あなたには目標にしている人物はいますか？",
      "あなたの最も自身のあるスキルを入力しましょう" => "あなたの得意なことは何ですか？",
      "あなたの最も成果を出した経験から、自身のあるスキルを入力しましょう" => "あなたの得意なことは何ですか？",
      "長所を入力しましょう！" => "あなたの長所は何ですか？",
      "自身の課題を入力しましょう" => "あなたがクリアするべきミッションを一つ上げてみましょう",
      "人から求められるスキルを確認しましょう" => "あなたが他の人から、最も求められているものは何ですか？",
      "キャリアの方向性を定めましょう！" => "あなたは今後、どんなキャリアを積むべきですか？",
    }
  end

  def questions_count
    questions.length
  end
end

app/helpers/tags/base_tag_helper.rb
module Tags::BaseTagHelper
end

app/helpers/tags/page_transitions_helper.rb
module Tags::PageTransitionsHelper
end

app/helpers/tags/question_assistances_helper.rb
module Tags::QuestionAssistancesHelper
  # 質問にリンクしたwcm
  def any_of_wcm
    [
      "will",
      "will",
      "will",
      "can",
      "can",
      "can",
      "must",
      "must",
      "must",
    ]
  end

  # questionの質問とヒント
  def questions
    {
      "理想の将来像を入力しましょう" => "あなたは将来、なりたいものはありますか？",
      "人生の中で一番重要視しているものを入力しましょう" => "スキル、お金、時間何を重視しますか？(この他でも解答可)",
      "その人のどういうところを目標としたいのか理由を入力しましょう" => "あなたには目標にしている人物はいますか？",
      "あなたの最も自身のあるスキルを入力しましょう" => "あなたの得意なことは何ですか？",
      "あなたの最も成果を出した経験から、自身のあるスキルを入力しましょう" => "あなたの得意なことは何ですか？",
      "長所を入力しましょう！" => "あなたの長所は何ですか？",
      "自身の課題を入力しましょう" => "あなたがクリアするべきミッションを一つ上げてみましょう",
      "人から求められるスキルを確認しましょう" => "あなたが他の人から、最も求められているものは何ですか？",
      "キャリアの方向性を定めましょう！" => "あなたは今後、どんなキャリアを積むべきですか？",
    }
  end

  # 質問数の制御
  def questions_count
    questions.length
  end

  # インディケータの制御
  def indicators_count
    questions_count + 1
  end
end

app/views/tags/question_assistances/create.js.erb
<%# モーダルの表示タグ置き換え %>
$('#assistancesTagContainer').html("<%= j(render partial: "layouts/flash", locals: { instance: @tags }) %>");

<%# エラーの表示のリフレッシュ %>
$('.js-message-errors').empty();
$('.flash').empty();

app/views/tags/question_assistances/create_errors.js.erb
$('.create-js-message-errors').replaceWith("<%= j(render "layouts/errors", instance: @tag) %>");

app/views/tags/question_assistances/new.html.erb
<div class="row mt-5 mb-5 pt-5 row">
  <div id="carouselExampleIndicators" class="carousel slide col-12" data-ride="carousel" data-interval="false">
    <div class="col-8 m-auto">
        <div class="carousel-inner">
          <div class="carousel-item active mb-3">
            <h4 class="mb-5">Will,Can,Mustに沿った質問に答えてカンタンに単語をアウトプットしましょう</h4>
            <p>・質問は<%= questions_count %>問です</p>
            <p>・なるべく単語でアウトプットしましょう(10文字以内)</p>
            <p>・答えかねる質問はスキップしましょう</p>
            <p>・答えた解答はそのままユーザーページのタグとして生成されます</p>
            <p>・タグはユーザーページから、自由に編集と作成できます</p>
            <h5>では、始めましょう！右側の > ボタンを押してスタート</h5>
          </div>
          <div id="assistancesTagContainer">
            <% if flash[:success].present? %>
              <div class="alert alert-success alert-dismissible fade show" role="alert"><%= flash[:success] %>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            <% end %>
          </div>
          <% questions.each.with_index(offset = 1) do |(k, v), i| %>
            <div class="carousel-item w-100">
            <%= form_with model: @tag, url: question_assistances_path do |f| %>
              <h3 class="mb-5" id="question"><%= v %></h3>
              <div class="create-js-message-errors"></div>
              <button type="button" value="" class="btn <%= any_of_wcm[i - 1] %>-color modal-btn show-btn will" ><%= any_of_wcm[i - 1] %></button>
                <%= f.label :name, "解答タグ: #{k}", for: "question_assistances#{i}" %>
                <%= f.text_field :tag, class: "form-control", id: "question_assistances#{i}" %>
                <%= f.hidden_field :question_body, value: k %>
                <%= f.hidden_field :wcm, value: any_of_wcm[i - 1] %>
                <div class="text-right mt-3">
                  <%= f.submit "作成", class: 'btn btn-outline-success', data: { disabled_with: '作成中' } %>
                </div>
            <% end %>
            </div>
          <% end %>
          <div class="carousel-item">
            <h4 class="mb-5">おつかれさまでした！</h4>
            <p>WCM簡単アウトプットは、これにて終了です。</p>
            <p>戻るボタンから、<%= @current_user.name %>さんのワークスペースに戻り</p>
            <p>ベースタグの設定や、目標設定を行っていきましょう！</p>
            <div class="text-right m-5">
              <%= link_to "戻る", user_path(@current_user), class: "btn btn-outline-success" %>
            </div>
          </div>
        </div>
    </div>
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="1" class="active bg-dark"></li>
      <% data_count = 1 %>
      <% indicators_count.times do %>
      <% data_count += 1 %>
        <li data-target="#carouselExampleIndicators" data-slide-to="<%= data_count %>" class="bg-dark" id="indicators<%= data_count %>"></li>
      <% end %>
    </ol>
    <div class="col-12 mb-5">
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev" onclick="prevDecision()">
        <i class="fas fa-chevron-left fa-2x text-dark" id="prev"></i>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next" onclick="nextDecision()">
        <i class="fas fa-chevron-right fa-2x text-dark" id="next"></i>
      </a>
    </div>
  </div>
</div>

app/views/tags/question_assistances/show.html.erb
<div class="row mt-5 pt-5 row">
  <div id="carouselExampleIndicators" class="carousel slide col-12" data-ride="carousel" data-interval="false">
    <div class="col-8 m-auto">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <h4 class="mb-5">Will,Can,Mustに沿った質問に答えてカンタンに単語をアウトプットしましょう</h4>
            <p>・質問は<%= questions_count %>問です</p>
            <p>・なるべく単語でアウトプットしましょう(10文字以内)</p>
            <p>・答えかねる質問はスキップしましょう</p>
            <p>・答えた解答はそのままユーザーページのタグとして生成されます</p>
            <p>・タグはユーザーページから、自由に編集と作成できます</p>
            <h5>では、始めましょう！右側の > ボタンを押してスタート</h5>
          </div>
          <% questions.each.with_index(offset = 1) do |(k, v), i| %>
            <div class="carousel-item w-100">
              <h3 class="mb-5"><%= v %></h3>
                <%= label_tag :name, "解答タグ: #{k}", for: "question_assistances" %>
                <%= text_field_tag :tag, nil, class: "form-control", id: "question_assistances#{i}" %>
            </div>
          <% end %>
          <div class="carousel-item w-100">
            <h2 class="mb-3">入力結果確認</h2>
            <%= form_with model: @tag, url: tags_path(@current_user.id), local: true do |f| %>
              <% questions.each.with_index(offset = 1) do |(k, v), i| %>
                <%= f.hidden_field :question_body, id: i + 1 %>
                <%= f.label v %>
                <%= f.text_field :tag, class: "form-control mb-3", id: "question_result#{i + 1}" %>
              <% end %>
              <div class="col-12 text-right">
                <%= f.submit "作成", class: 'btn btn-outline-success' %>
              </div>
            <% end %>
          </div>
        </div>
    </div>
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active bg-dark"></li>
      <% questions.each.with_index do |h, c| %>
        <li data-target="#carouselExampleIndicators" data-slide-to="<%= c + 1 %>" class="bg-dark"></li>
      <% end %>
    </ol>
    <div class="col-12 mb-5">
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <i class="fas fa-chevron-left fa-2x text-dark"></i>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <i class="fas fa-chevron-right fa-2x text-dark"></i>
      </a>
    </div>
  </div>
</div>